### ISSUE TITLE
Failed to    npm install android-unicode --save

### ISSUE THREAD

**Issue by gongfen** [macacajs/android-unicode#5]
sudo npm i macaca-android --save

> android-unicode@1.0.9 install /Users/admin/node_modules/android-unicode
> node ./script/build.js

Error: $JAVA_HOME is not set
    at checkJavaHome.then.catch.then.then.catch.then.std (/Users/admin/node_modules/java-home/lib/java-home.js:89:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/Users/admin/node_modules/android-unicode/script/build.js:15
    throw e;
    ^

Error: $JAVA_HOME is not set
    at checkJavaHome.then.catch.then.then.catch.then.std (/Users/admin/node_modules/java-home/lib/java-home.js:89:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm WARN enoent ENOENT: no such file or directory, open '/Users/admin/package.json'
npm WARN admin No description
npm WARN admin No repository field.
npm WARN admin No README data
npm WARN admin No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-android" "--save"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.9 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-unicode@1.0.9 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

---split line-----then install android-unicode,failed again -------------

sudo npm install android-unicode

> android-unicode@1.0.9 install /Users/admin/node_modules/android-unicode
> node ./script/build.js

Error: $JAVA_HOME is not set
    at checkJavaHome.then.catch.then.then.catch.then.std (/Users/admin/node_modules/java-home/lib/java-home.js:89:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/Users/admin/node_modules/android-unicode/script/build.js:15
    throw e;
    ^

Error: $JAVA_HOME is not set
    at checkJavaHome.then.catch.then.then.catch.then.std (/Users/admin/node_modules/java-home/lib/java-home.js:89:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm WARN enoent ENOENT: no such file or directory, open '/Users/admin/package.json'
npm WARN admin No description
npm WARN admin No repository field.
npm WARN admin No README data
npm WARN admin No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "android-unicode"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.9 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-unicode@1.0.9 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/npm-debug.log

**Comment by gongfen** [comment]
因为我没有 no such file or directory, open '/Users/admin/package.json'
手动创建一个就好了npm init
